version: '3.8'

services:
  postgres_clothing_store:
    image: postgres:16-alpine
    container_name: ejb-clothing-store-db
    ports:
      - "5438:5432"
    environment:
      POSTGRES_DB: clothing_store
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./docker-volume:/var/lib/postgresql/data

volumes:
  postgres_clothing_store_data:
    driver: local